import { TestBed } from '@angular/core/testing';
import { ReviewGalleryComponent } from './review-gallery.component';

describe('ReviewGallery', () => {
  beforeEach(() => jasmine.clock().install());
  afterEach(() => jasmine.clock().uninstall());
  it('advances, pauses during interaction, and resets after changing photos', () => {
    const fixture=TestBed.createComponent(ReviewGalleryComponent);
    fixture.componentRef.setInput('photos',[{url:'one.jpg'},{url:'two.jpg'}]);
    fixture.detectChanges();
    const c=fixture.componentInstance;
    c.paused.set(false);
    jasmine.clock().tick(6500);
    expect(c.index()).toBe(1);
    c.hovered=true;
    jasmine.clock().tick(6500);
    expect(c.index()).toBe(1);
    c.move(1);
    expect(c.index()).toBe(0);
    c.select(1);
    fixture.componentRef.setInput('photos',[{url:'new.jpg'}]);
    fixture.detectChanges();
    expect(c.index()).toBe(0);
    fixture.destroy();
  });
  it('shows the current note as text and keeps the selected image when its caption is edited', () => {
    const fixture = TestBed.createComponent(ReviewGalleryComponent);
    fixture.componentRef.setInput('photos',[{url:'one.jpg',caption:''},{url:'two.jpg',caption:'ฉากที่ชอบ\n<script>example</script>'}]);
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('figcaption')).toBeNull();
    fixture.componentInstance.select(1);
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('figcaption p').textContent).toContain('\n<script>example</script>');
    expect(fixture.nativeElement.querySelector('figcaption script')).toBeNull();
    fixture.componentRef.setInput('photos',[{url:'one.jpg',caption:''},{url:'two.jpg',caption:'Updated note'}]);
    fixture.detectChanges();
    expect(fixture.componentInstance.index()).toBe(1);
    expect(fixture.nativeElement.querySelector('figcaption p').textContent).toBe('Updated note');
    fixture.componentInstance.open();
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('dialog .memory-note p').textContent).toBe('Updated note');
    fixture.componentInstance.lightbox()!.nativeElement.close();
    fixture.destroy();
  });
  it('pauses automatic slides while the full note is expanded', () => {
    const fixture = TestBed.createComponent(ReviewGalleryComponent);
    fixture.componentRef.setInput('photos',[{url:'one.jpg',caption:'คำอธิบายยาว '.repeat(40)},{url:'two.jpg',caption:''}]);
    fixture.detectChanges();
    fixture.componentInstance.paused.set(false);
    fixture.nativeElement.querySelector('.read-note').click();
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('figcaption .collapsed')).toBeNull();
    jasmine.clock().tick(6500);
    expect(fixture.componentInstance.index()).toBe(0);
    fixture.componentInstance.move(1);
    fixture.detectChanges();
    expect(fixture.componentInstance.expanded()).toBeFalse();
    expect(fixture.nativeElement.querySelector('figcaption')).toBeNull();
    fixture.destroy();
  });
});
